pipeline {
  agent any
  stages {
    stage('download dependencies') {
      steps {
        bat 'npm ci'
      }
    }
    
    stage('Check for vulnerabilities') {
      steps {
        bat 'npm audit --parseable --production'
      }
    }

    stage('Build') {
      steps {
        bat 'npm run build'
      }
    }
  }
}
