pipeline {
  agent any
  stages {
    stage('download dependencies') {
      steps {
        bat 'npm ci'
      }
    }
    
    stage('Check for vulnerabilities') {
      steps {
        bat 'npm audit --parseable --production'
      }
    }

    stage('Check unit:test') {
      steps {
        bat 'npm run test:unit -- --ci --coverage'
      }
      post {
        always {
          junit 'junit.xml'
          cobertura coberturaReportFile: 'coverage/cobertura-coverage.xml'
        }
      }
    }

    stage('Build') {
      steps {
        bat 'npm run build'
      }
    }
  }
}
